blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),  # Создание статьи
    path('', BlogListView.as_view(), name='list'),  # Вывод всех статей
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),  # Изменеие статьи
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),  # Просмотр статьи
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),  # Удаление статьи
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Article(models.Model):
    """
    Модель "Статья"
    """

    title = models.CharField(max_length=150, verbose_name='Заголовок', **NULLABLE)
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Cодержимое', **NULLABLE)
    preview = models.ImageField(upload_to='media/', verbose_name='Превью статьи', **NULLABLE)
    article_date_creation = models.DateTimeField(auto_now_add=True)
    publication = models.BooleanField(default=True, verbose_name='Признак публикации', null=True, blank=True)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/forms.py
from django import forms

from blog.models import Article
from mailing.forms import StyleFormMixin


class ArticleForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания и изменения статей блога
    """
    class Meta:
        model = Article
        exclude = ('publication', 'views_count',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify

from blog.forms import ArticleForm
from blog.models import Article


class BlogCreateView(CreateView):
    """
    Создает новый экземпляр модели "Статья"
    """
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:list')

    # Динамически формируем slug name
    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    """
    Выводит все статьи на страницу
    """
    model = Article

    # Выводит только активные статьи
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogUpdateView(UpdateView):
    """
    Позволяет изменить существующие статьи
    """
    model = Article
    form_class = ArticleForm

    # Динамически формируем slug name
    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    # После обнавления перенаправляет на статью
    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    """
    Выводит статью целиком
    """
    model = Article

    # Счетчик просмотров
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    """
    Удаляет элемент
    """
    model = Article
    success_url = reverse_lazy('blog:list')

blog/templates/blog/article_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <p> Хотите удалить статью "{{ object.title }}"?</p>
                                    <button type="submit" class="btn btn-danger">
                                        Подтвердить
                                    </button>
                                    <a href="{% url 'blog:list' %}" class="btn btn-warning"> Отмена </a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    {{ object.title }} ({{ object.slug }})
                                </h3>
                            </div>
                            <div class="card-body">
                                <table class="table">
                                    <tr>
                                        <td>{{ object.body }}</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="card-footer">
                                Прочитано {{ object.views_count }} раз.
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <img src="/media/{{ object.preview }}" height="100%" width="100%"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/article_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-body">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    {% if object %}
                                        <button type="submit" class="btn btn-primary">соханить</button>
                                    {% else %}
                                        <button type="submit" class="btn btn-primary">создать</button>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'mailing/base.html' %}
{% load image_teg %}


{% block content %}

    <section class="py-5 text-center container" xmlns="http://www.w3.org/1999/html">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Статьи блога.</h1><br>
                <p>
                    <a class="btn btn-primary bg-dark" href="{% url 'blog:create' %}">Добавить новую статью</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for object in object_list %}
                    {% include 'blog/include/inc_blog_detail.html' %}

                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}