blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),  # Создание статьи
    path('', BlogListView.as_view(), name='list'),  # Вывод всех статей
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),  # Изменеие статьи
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),  # Просмотр статьи
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),  # Удаление статьи
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verification_user, password_recovery, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),  # Авторизация пользователя
    path('logout/', LogoutView.as_view(), name='logout'),  # Выход пользователя
    path('register/', RegisterView.as_view(), name='register'),  # Регистрация пользователя
    path('success_register/<str:register_uuid>/', verification_user, name='success_register'),  # Верификация пользователя
    path('password_recovery', password_recovery, name='password_recovery'),  # Восстановление доступа с помощью сгенерированного пароля и электронной почты
    path('profile/', UserUpdateView.as_view(), name='profile'),  # Изменение данных о пользователе
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.models import NULLABLE


class User(AbstractUser):
    """
    Модель "Пользователь"
    Для авторизации пользователя используется email
    """
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватаp', **NULLABLE)
    register_uuid = models.CharField(max_length=50, verbose_name='register_uuid', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма для регистрации пользователя
    """

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    """
    Форма для редактирования данных о пользователе
    """

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """
        Скрывает изменение пароля
        """
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import uuid
import random

from django.conf import settings
from django.contrib.auth import login
from django.contrib.sites.shortcuts import get_current_site
from django.core.checks import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User


class LoginView(BaseLoginView):
    """
    Авторизация пользователя
    """
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    """
    Выход пользователя
    """
    pass


class RegisterView(CreateView):
    """
    Регистрация нового пользователя
    """
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """
        После регистрации отправляет на электронную почту ссылку для верификации аккаунта
        """
        if form.is_valid():
            self.object = form.save()
            self.object.is_active = False
            self.object.register_uuid = uuid.uuid4().hex
            self.object.save()
            current_site = get_current_site(self.request)
            send_mail(
                subject='Подтверждение аккаунта',
                message=f'Для подтверждения перейдите по ссылке http://{current_site}{reverse_lazy("users:success_register", kwargs={"register_uuid": self.object.register_uuid})}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )
        return super().form_valid(form)


def verification_user(request, *args, **kwargs):
    """
    Верификации аккаунта после перехода по ссылке с электронной почты
    """
    user = User.objects.get(register_uuid=kwargs["register_uuid"])
    if user.register_uuid == kwargs['register_uuid']:
        user.is_active = True
        user.save()
        login(request, user)
    return redirect(reverse('mailing:main'))


def password_recovery(request):
    """
    Восстановление доступа с помощью сгенерированного пароля отправленного на электронную почту
    """
    if request.method == 'POST':
        email = request.POST.get('email')
        users = User.objects.all()
        for user in users:
            if user.email == email:
                new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
                send_mail(
                    subject='Восстановление пароля',
                    message=f'Ваш новый пароль: {new_password}',
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[user.email]
                )
                user.set_password(new_password)
                user.save()
                return redirect(reverse('users:login'))
    return render(request, 'users/password_recovery.html')


class UserUpdateView(UpdateView):
    """
    Изменение параметров пользователя
    """
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """
        Получение авторизованного пользователя
        """
        return self.request.user

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Войти</div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Вход</button>
                                <a class="btn btn-danger" type="button" href="{% url 'users:password_recovery' %}">Восстановить пароль</a>
                            </form>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Укажите EMAIL:</div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input class="form-control mb-2" name="email">
                                <button type="submit" class="btn btn-primary form-control">Восстановить</button>
                            </form>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Регистрация</div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Регистрация</button>
                            </form>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Профиль</div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </form>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}