blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),  # Создание статьи
    path('', BlogListView.as_view(), name='list'),  # Вывод всех статей
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),  # Изменеие статьи
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),  # Просмотр статьи
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),  # Удаление статьи
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import main, MailingCreateView, MailingListView, MailingDetailView, MailingUpdateView, \
    MailingDeleteView

app_name = MailingConfig.name

urlpatterns = [
    path('', main, name='main'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('mailing/', cache_page(60)(MailingListView.as_view()), name='mailing'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='view'),
    path('mailing/update/<int:pk>/', MailingUpdateView.as_view(), name='update'),
    path('mailing/delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verification_user, password_recovery, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),  # Авторизация пользователя
    path('logout/', LogoutView.as_view(), name='logout'),  # Выход пользователя
    path('register/', RegisterView.as_view(), name='register'),  # Регистрация пользователя
    path('success_register/<str:register_uuid>/', verification_user, name='success_register'),  # Верификация пользователя
    path('password_recovery', password_recovery, name='password_recovery'),  # Восстановление доступа с помощью сгенерированного пароля и электронной почты
    path('profile/', UserUpdateView.as_view(), name='profile'),  # Изменение данных о пользователе
]

mailing/models.py
from django.db import models

#
NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    """
    Модель клиента, кому будет отправляться сообщение
    """
    email = models.CharField(max_length=250, verbose_name='email')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Massage(models.Model):
    """
    Модель сообщения
    """
    mail_subject = models.CharField(max_length=300, verbose_name='тема письма')
    text = models.TextField(verbose_name='тело письма')

    def __str__(self):
        return self.mail_subject

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class Mailing(models.Model):
    """
    Модель рассылки
    """
    INTERVAL = [('day', 'каждый день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')]
    STATUS = [('create', 'создана'), ('start', 'запущена'), ('finished', 'завершена')]
    name = models.CharField(max_length=150, verbose_name='название рассылки')
    start = models.DateField(verbose_name='начало рассылки')
    stop = models.DateField(verbose_name='конец рассылки')
    interval = models.CharField(max_length=5, choices=INTERVAL, default='day')
    status_mail = models.CharField(max_length=8, choices=STATUS, default='create')
    users_group = models.ManyToManyField(Customer, verbose_name='группа пользователей для рассылки')
    massage = models.ForeignKey(Massage, on_delete=models.SET_NULL, null=True, verbose_name='письмо')
    datetime = models.DateField(auto_now_add=True, verbose_name='дата и время попытки')
    attempt = models.BooleanField(default=False, verbose_name='статус попытки')
    feedback = models.TextField(verbose_name='ответ сервера', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

mailing/forms.py
from django import forms

from mailing.models import Mailing


class StyleFormMixin:
    """
    Стиль для отображения формы заполнения
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('status_mail', 'attempt', 'feedback',)

mailing/views.py
import datetime

from django.conf import settings
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Article
from mailing.forms import MailingForm
from mailing.models import Mailing, Massage, Customer


def main(request):
    """
    Переходит на страницу "Главная"
    """
    mailing_count = len(Mailing.objects.all())
    mailing_active = len(Mailing.objects.filter(status_mail='start'))
    customer_count = len(Customer.objects.all())
    blog_list = Article.objects.order_by('?')[:3]
    context = {'mailing_count': mailing_count,
               'mailing_active': mailing_active,
               'customer_count': customer_count,
               'blog_list': blog_list}
    return render(request, 'mailing/main.html', context)


class MailingCreateView(CreateView):
    """
    Создание рассылки
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:main')

    def form_valid(self, form):

        """
        Проверка текущей даты, с датой начала и окончания рассылки.
        """
        if form.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            day_today = datetime.date.today()
            if self.object.start <= day_today < self.object.stop:
                self.object.status_mail = 'start'
                mail = self.object.massage
                users = self.object.users_group.all()
                for user in users:
                    send_mail(
                        subject=mail.mail_subject,
                        message=mail.text,
                        from_email=settings.EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )
                self.object.datatime = day_today
            elif day_today > self.object.stop:
                self.object.status_mail = 'finished'
            self.object.save()
            return super().form_valid(form)


class MailingListView(ListView):
    """
    Отображение всех рассылок
    """
    model = Mailing


class MailingDetailView(DetailView):
    """
    Просмотр информации о рассылке
    """
    model = Mailing


class MailingUpdateView(UpdateView):
    """
    Изменение параметров рассылки
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing')


class MailingDeleteView(DeleteView):
    """
    Удаление рассылки
    """
    model = Mailing
    success_url = reverse_lazy('mailing:mailing')

mailing/templates/mailing/include/inc_mailing_detail.html
<div class="col">
    <div class="card mb-4 shadow-sm">
        <div class="card-header">
            <p class="card-text">{{ object.name }}</p>
        </div>
        <div class="card-body">
            <div class="card-footer">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'mailing:view' object.pk %}">Подробнее</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'mailing:update' object.pk %}">Изменить</a>
                        <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'mailing:delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

mailing/templates/mailing/include/inc_mailing_menu.html
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94"
             role="img"><title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                  fill="currentColor"></path>
        </svg>
        <span class="fs-4">Управление рассылками</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'mailing:create' %}">Создать</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'mailing:mailing' %}">Все рассылки</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'blog:list' %}">Блог</a>
        {% if user.is_authenticated %}
        <a href="{% url 'users:profile' %}" class="me-3 py-2 text-dark text-decoration-none">Профиль</a>
        <a href="{% url 'users:logout' %}" class="me-3 py-2 text-dark text-decoration-none">Выйти</a>
        {% else %}
        <a href="{% url 'users:login' %}" class="me-3 py-2 text-dark text-decoration-none">Войти</a>
        <a href="{% url 'users:register' %}" class="me-3 py-2 text-dark text-decoration-none">Регистрация</a>
        {% endif %}
    </nav>
</div>

mailing/templates/mailing/include/inc_mailing_style.html
.bd-placeholder-img {
font-size: 1.125rem;
text-anchor: middle;
-webkit-user-select: none;
-moz-user-select: none;
user-select: none;
}

@media (min-width: 768px) {
.bd-placeholder-img-lg {
font-size: 3.5rem;
}
}